//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PURCHASE.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PURCHASE.Resource.GeneralData", typeof(GeneralData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更成功！.
        /// </summary>
        internal static string Add_CN {
            get {
                return ResourceManager.GetString("Add_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Successlly!.
        /// </summary>
        internal static string Add_EN {
            get {
                return ResourceManager.GetString("Add_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công!.
        /// </summary>
        internal static string Add_VN {
            get {
                return ResourceManager.GetString("Add_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除成功！.
        /// </summary>
        internal static string Del_CN {
            get {
                return ResourceManager.GetString("Del_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Successfully !.
        /// </summary>
        internal static string Del_EN {
            get {
                return ResourceManager.GetString("Del_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Thành Công !.
        /// </summary>
        internal static string Del_VN {
            get {
                return ResourceManager.GetString("Del_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功修復 !.
        /// </summary>
        internal static string Edit_CN {
            get {
                return ResourceManager.GetString("Edit_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Successfully !.
        /// </summary>
        internal static string Edit_EN {
            get {
                return ResourceManager.GetString("Edit_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Thành Công !.
        /// </summary>
        internal static string Edit_VN {
            get {
                return ResourceManager.GetString("Edit_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能為空！.
        /// </summary>
        internal static string NotEnter_CN {
            get {
                return ResourceManager.GetString("NotEnter_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not be empty!.
        /// </summary>
        internal static string NotEnter_EN {
            get {
                return ResourceManager.GetString("NotEnter_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được bỏ trống!.
        /// </summary>
        internal static string NotEnter_VN {
            get {
                return ResourceManager.GetString("NotEnter_VN", resourceCulture);
            }
        }
    }
}
